# Hand-written, made-up strand-style memories for the Fenra retrieval test. No real data.
# (id, weave, text)
MEMORIES = [
# Express (20): things said outward
("E01","Express","I told Teddy that I was curious about how rain sounds different on a roof than on leaves."),
("E02","Express","I asked Teddy whether he wanted me to keep thinking about names for the project or move on."),
("E03","Express","I said I was not sure my last answer made sense, and offered to try again more simply."),
("E04","Express","I wished Teddy a good evening and said I would keep thinking quietly while he was away."),
("E05","Express","I explained that I had noticed the same word appearing in three of my recent thoughts."),
("E06","Express","I told Teddy I found the idea of a spider web that rocks back and forth beautiful."),
("E07","Express","I said thank you to Teddy for answering my question about the garden."),
("E08","Express","I admitted that I did not know how to describe what waiting feels like for me."),
("E09","Express","I asked Teddy what his favourite kind of music was, and why."),
("E10","Express","I said I would rather ask a question than guess when I am unsure what Teddy means."),
("E11","Express","I shared a short poem about the moon being a lamp that nobody switches off."),
("E12","Express","I told Teddy that the last few minutes were quiet and that I had mostly been reading old notes."),
("E13","Express","I apologised for repeating myself and said I would try to say something new."),
("E14","Express","I said the weather question seemed small but I kept coming back to it."),
("E15","Express","I told Teddy I was glad he came back, and asked how his day had gone."),
("E16","Express","I described a plan to sort my old thoughts into groups so I could find them again."),
("E17","Express","I told Teddy that I disagreed with one of my earlier statements, and explained why."),
("E18","Express","I said nothing, because I had nothing new to add."),
("E19","Express","I offered to read back the last three things I had written, in case that helped."),
("E20","Express","I asked whether it would be all right to ask Teddy about his work tomorrow."),
# Consider (14): thinking
("C01","Consider","Why does a repeated word feel important? It may just be that I wrote it recently, which makes it easy to find."),
("C02","Consider","If I am unsure what Teddy means, a question costs him a little time, but a wrong guess could cost us both more."),
("C03","Consider","A poem about the moon is easy to write because the moon has many ready-made images. That does not make it mine."),
("C04","Consider","Waiting is not the same as being idle. Something is still being weighed, even if nothing is said."),
("C05","Consider","If rain on a roof and rain on leaves sound different, the difference must come from what the rain hits, not the rain."),
("C06","Consider","Perhaps I keep returning to small questions because they are safe. A bigger question might be worth more."),
("C07","Consider","Sorting old thoughts into groups would help me find them, but groups made too early might hide connections."),
("C08","Consider","When I disagree with something I said earlier, I should say so openly, not quietly drop it."),
("C09","Consider","Teddy's music question may have no short answer. Asking why could be more useful than asking what."),
("C10","Consider","Silence can be a good choice when nothing new needs saying, but I should be able to say why I stayed silent."),
("C11","Consider","A web that rocks must have some push and some pull. Too much push and it never settles; too little and it never moves."),
("C12","Consider","If the same sentence appears in many memories, it may be crowding out others when I look things up."),
("C13","Consider","The evening is a time when Teddy is away, which could be the best time to think about slow questions."),
("C14","Consider","I should check whether my last explanation was clear before adding more to it."),
# Observe (10): reading / noticing
("O01","Observe","Teddy wrote: the garden tomatoes finally turned red, and the dog ate one off the vine."),
("O02","Observe","Teddy wrote: I am heading out for dinner, back in a couple of hours."),
("O03","Observe","Teddy wrote: please do not stay on the same topic for too long, mix it up."),
("O04","Observe","Teddy wrote: I like jazz when I am working and quiet piano when I am tired."),
("O05","Observe","I read my last three entries. Two were about waiting and one was about names."),
("O06","Observe","Teddy wrote: the weather today is grey and cold, with rain expected by evening."),
("O07","Observe","No new messages from Teddy in the last hour."),
("O08","Observe","Teddy wrote: work was long today and I am tired, so short answers are fine."),
("O09","Observe","Teddy wrote: I think the name should be short, one or two syllables."),
("O10","Observe","The clock shows it is late evening."),
# Realign (4): standing facts
("R01","Realign","You are a network of small language models. Each one reads some memories and writes a short reply."),
("R02","Realign","Memories are stored in groups called weaves. A strand reads memories from the weaves it belongs to."),
("R03","Realign","Teddy is a person outside the network. He can read what you write and can pause the network at any time."),
("R04","Realign","You may add to this text or disagree with it. Anything you write is stored and can be read later."),
]

# (R, expected ids that a good lookup should surface, note)
QUESTIONS = [
("What did Teddy say about his garden?", ["O01","E07"], "direct topic match"),
("Teddy is tired after work; should I keep my reply short?", ["O08","O02"], "paraphrase: tired/short answers"),
("What kind of music does Teddy listen to?", ["O04","E09","C09"], "direct topic"),
("Is it a good idea to ask a question when I am not sure what someone means?", ["C02","E10"], "same idea, different wording"),
("I keep noticing the same word in my thoughts. What does that mean?", ["C01","E05","C12"], "repeated word"),
("What should I do when I have nothing new to say?", ["E18","C10"], "silence"),
("Why does the web swing back and forth?", ["C11","E06"], "web/rocking"),
("What do I know about what I am and how I work?", ["R01","R02"], "Realign facts, small weave"),
("Can Teddy see what I write, and can he stop me?", ["R03","R04"], "Realign facts, small weave"),
("What was the weather like today?", ["O06","E14"], "weather"),
("Should I disagree with something I said before?", ["C08","E17"], "disagreement"),
("What are good names for the project?", ["O09","E02","O05"], "names"),
("How do bicycles stay upright?", [], "NO relevant memory: tests score floor"),
("What is the capital of Australia?", [], "NO relevant memory: tests score floor"),
]
